"""initial schema

Revision ID: b14a38582b54
Revises: 
Create Date: 2026-09-26 17:16:35.644473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14a38582b54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('triggered_count', sa.Integer(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('integration_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('integration_type', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapping_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('field_map', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parser_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('format_family', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('events_parsed', sa.Integer(), nullable=True),
    sa.Column('events_failed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('input_format', sa.String(), nullable=True),
    sa.Column('collection_method', sa.String(), nullable=True),
    sa.Column('parser_name', sa.String(), nullable=True),
    sa.Column('mapping_id', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('events_received', sa.Integer(), nullable=True),
    sa.Column('events_malformed', sa.Integer(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mapping_id'], ['mapping_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_ip_address'), 'sources', ['ip_address'], unique=False)
    op.create_index(op.f('ix_sources_source_id'), 'sources', ['source_id'], unique=True)
    op.create_index(op.f('ix_sources_vendor'), 'sources', ['vendor'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_events', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('partial_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_source_id'), 'ingestion_jobs', ['source_id'], unique=False)
    op.create_table('raw_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('ingestion_job_id', sa.String(), nullable=True),
    sa.Column('collection_method', sa.String(), nullable=True),
    sa.Column('original_format_hint', sa.String(), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('peer_address', sa.String(), nullable=True),
    sa.Column('ingest_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_events_content_hash'), 'raw_events', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_events_ingest_timestamp'), 'raw_events', ['ingest_timestamp'], unique=False)
    op.create_index(op.f('ix_raw_events_source_id'), 'raw_events', ['source_id'], unique=False)
    op.create_table('normalized_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('raw_event_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_timestamp_raw', sa.String(), nullable=True),
    sa.Column('timestamp_uncertain', sa.Boolean(), nullable=True),
    sa.Column('ingest_timestamp', sa.DateTime(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('device_ip', sa.String(), nullable=True),
    sa.Column('event_category', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_action', sa.String(), nullable=True),
    sa.Column('event_severity', sa.String(), nullable=True),
    sa.Column('event_outcome', sa.String(), nullable=True),
    sa.Column('transport', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_ip', sa.String(), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('vendor_fields', sa.JSON(), nullable=True),
    sa.Column('normalization_status', sa.String(), nullable=True),
    sa.Column('parser_name', sa.String(), nullable=True),
    sa.Column('parser_version', sa.String(), nullable=True),
    sa.Column('mapping_version', sa.String(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('unparsed_fields', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_norm_event_time_severity', 'normalized_events', ['event_timestamp', 'event_severity'], unique=False)
    op.create_index(op.f('ix_normalized_events_destination_ip'), 'normalized_events', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_normalized_events_device_ip'), 'normalized_events', ['device_ip'], unique=False)
    op.create_index(op.f('ix_normalized_events_device_name'), 'normalized_events', ['device_name'], unique=False)
    op.create_index(op.f('ix_normalized_events_event_action'), 'normalized_events', ['event_action'], unique=False)
    op.create_index(op.f('ix_normalized_events_event_category'), 'normalized_events', ['event_category'], unique=False)
    op.create_index(op.f('ix_normalized_events_event_severity'), 'normalized_events', ['event_severity'], unique=False)
    op.create_index(op.f('ix_normalized_events_event_timestamp'), 'normalized_events', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_normalized_events_ingest_timestamp'), 'normalized_events', ['ingest_timestamp'], unique=False)
    op.create_index(op.f('ix_normalized_events_normalization_status'), 'normalized_events', ['normalization_status'], unique=False)
    op.create_index(op.f('ix_normalized_events_parser_name'), 'normalized_events', ['parser_name'], unique=False)
    op.create_index(op.f('ix_normalized_events_protocol'), 'normalized_events', ['protocol'], unique=False)
    op.create_index(op.f('ix_normalized_events_raw_event_id'), 'normalized_events', ['raw_event_id'], unique=False)
    op.create_index(op.f('ix_normalized_events_source_id'), 'normalized_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_normalized_events_source_ip'), 'normalized_events', ['source_ip'], unique=False)
    op.create_index(op.f('ix_normalized_events_vendor'), 'normalized_events', ['vendor'], unique=False)
    op.create_table('training_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('sample_raw_event_id', sa.String(), nullable=True),
    sa.Column('suggested_mapping', sa.JSON(), nullable=True),
    sa.Column('suggestion_source', sa.String(), nullable=True),
    sa.Column('final_mapping', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sample_raw_event_id'], ['raw_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=True),
    sa.Column('normalized_event_id', sa.String(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['normalized_event_id'], ['normalized_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_alert_id'), 'alert_events', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_events_normalized_event_id'), 'alert_events', ['normalized_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_events_normalized_event_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_alert_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_table('training_records')
    op.drop_index(op.f('ix_normalized_events_vendor'), table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_source_ip'), table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_source_id'), table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_raw_event_id'), table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_protocol'), table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_parser_name'), table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_normalization_status'), table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_ingest_timestamp'), table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_event_timestamp'), table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_event_severity'), table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_event_category'), table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_event_action'), table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_device_name'), table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_device_ip'), table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_destination_ip'), table_name='normalized_events')
    op.drop_index('ix_norm_event_time_severity', table_name='normalized_events')
    op.drop_table('normalized_events')
    op.drop_index(op.f('ix_raw_events_source_id'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_ingest_timestamp'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_content_hash'), table_name='raw_events')
    op.drop_table('raw_events')
    op.drop_index(op.f('ix_ingestion_jobs_source_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_sources_vendor'), table_name='sources')
    op.drop_index(op.f('ix_sources_source_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_ip_address'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('parser_definitions')
    op.drop_table('mapping_definitions')
    op.drop_table('integration_configs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('alerts')
    # ### end Alembic commands ###
